## 3 - Criar um Deployment

# Um Deployment gerencia a criação e atualização de Pods e ReplicaSets, garantindo que a versão desejada dos Pods esteja sempre em execução.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80