## 1. Criar um Pod

# O primeiro passo é criar um Pod, que é a menor unidade executável no Kubernetes. Ele pode conter um ou mais containers.

apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    name: nginx
spec:
  containers:
  - name: nginx
    image: nginx:latest      
    ports:
      - containerPort: 80
