## 2 - Criar um ReplicaSet

# Um ReplicaSet garante que um número especificado de réplicas de um Pod esteja em execução a qualquer momento.

apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-replicaset
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: wesleywillians/nginx-imersao13      
        ports:
        - containerPort: 80
