## 4. Criar um Service

# Um Service expõe um ou mais Pods para a rede interna ou externa, facilitando o balanceamento de carga e acesso aos Pods.

apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: LoadBalancer
  selector:
    app: nginx
  ports:
  - port: 80
    targetPort: 80
